packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.0.1
  '@types/mdx': 2.0.13
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  'next': 15.0.2
  'react': 19.0.0-rc-02c0e824-20241028
  'react-dom': 19.0.0-rc-02c0e824-20241028
  'restyle': 2.4.0
  'shiki': 1.22.1
  'webpack': 5.95.0
