packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.0.1
  '@mdx-js/react': 3.0.1
  '@next/mdx': 14.2.7
  '@types/mdx': 2.0.13
  '@types/react': 18.3.4
  '@types/react-dom': 18.3.0
  'next': 14.2.7
  'react': 18.3.1
  'react-dom': 18.3.1
  'restyle': 2.1.0
